### PR TITLE
nightly notification deletion: make tests more tolerant of iteration order

### PR DESCRIPTION
**Pull request by risicle**
Fixup from #4210

### CODE REVIEW

**Comment by quis** [comment]
Shouldn’t this line mean the tests don’t need the order to be deterministic?
https://github.com/alphagov/notifications-api/blob/c55790e45d62fe26f96707943e0d58c9eabfdd9f/tests/app/celery/test_nightly_tasks.py#L566

**Comment by risicle** [comment]
The issue is that in the tested code, the `countdown=` numbers are assigned based on iteration order, and without special attention getting the correct `countdown=` value paired up with the right service uuid is 50/50

**Review by quis — APPROVED** [review]
Ah, got it, so it doesn’t matter which service gets which countdown value.

**Comment by risicle** [comment]
Nope.

**Pull request merged**
