### PR TITLE
Remove some unused code

### PR DESCRIPTION
**Pull request by leohemsted**
None of these endpoints or functions are used anywhere

Well, `get_notification_statistics_for_service_for_day` (`/service/{}/notifications-statistics/day/{}`) is referenced in notifications-admin but not actually called from any pages

### CODE REVIEW

**Comment by minglis** [comment]
Good call on deleting this stuff, It's all read isn't it?

**Comment by leohemsted** [comment]
yup, update_platform_stats not affected by this PR. i'll fix merge conflicts

**Comment by minglis** [comment]
OK ship it 👍

**Comment by leohemsted** [comment]
build passing see https://jenkins.notify.tools/job/notifications-api/60/console

**Pull request merged**
