### PR TITLE
actually bump version

### PR DESCRIPTION
**Pull request by leohemsted**
missed a number last time 😧

### CODE REVIEW

**Comment by leohemsted** [comment]
note: this is actually testable - see https://travis-ci.org/alphagov/notifications-api/builds/154153273#L400

we download 8.7.6

**Comment by quis** [comment]
I’ve made this mistake so many times. Is there any reason we need the `egg=…` bit?

**Comment by leohemsted** [comment]
good point - doesn't appear to be required at first glance but i'll check more thoroughly later

**Comment by leohemsted** [comment]
@quis it appears that if you don't provide the `#egg` it clones the entire repository and fetches every tag before selecting the right one 😐

**Pull request merged**
