### PR TITLE
Add validation to prevent blank area names

### PR DESCRIPTION
**Pull request by benthorner**
https://www.pivotaltracker.com/story/show/178986763

Now that these are used for display on gov.uk/alerts we need to
make sure the data is being set properly. We've already found an
example where it wasn't [1]. We validate external broadcasts in
two stages: with the official CAP XML schema [2] and then again
with our own, more specific schema for the converted JSON. Since
this validation is a custom requirement I've made it part of the
JSON schema. Note that jsonschema recommends avoiding metachars
like "\w" since they're not supported by all implementations [3].

I've tested the new validation manually and it works as expected
by disallowing e.g. "  " but still alowing "foo" and "foo bar".
I don't think we need a test for it, as it's declarative code
for an edge case concern.

[1]: https://www.notifications.service.gov.uk/services/120107d0-d99a-4c42-8b70-f37d2f28879b/rejected-alerts/d6e0c70e-60f6-4422-8589-2a2d159c63f2
[2]: https://github.com/alphagov/notifications-api/blob/81a25ff1effa821f0096fcc5edea79b0a5b17f5e/app/xml_schemas/CAP-v1.2.xsd
[3]: http://json-schema.org/understanding-json-schema/reference/regular_expressions.html

### CODE REVIEW

**Comment by leohemsted** [comment]
Great fix 👍 

Worth pointing out that we may well expect more in the future, I'm not sure we've got a concrete plan on what to do ~~if~~ when electoral areas change. I think it's reasonable to expect that electoral wards may well merge or be renamed in due course.

**Comment by benthorner** [comment]
Update: after discussing with the team I've modified this PR and the new validation is now just one line in the JSON schema for external broadcasts. I've kept the first couple of commits as I think they still add a little value.

**Review by CrystalPea — COMMENTED** [review]
The regex looks good to me 👍🏼 . Shouldn't we have some test for this though?

**Comment by benthorner** [comment]
@CrystalPea we could do and I did have one originally. The third commit message has more:

> I've tested the new validation manually and it works as expected
> by disallowing e.g. "  " but still alowing "foo" and "foo bar".
> I don't think we need a test for it, as it's declarative code
> for an edge case concern.

I don't feel too strongly about this, although I think it's worth asking: there are lots of other definitions and settings in that schema and the XML one that we validate with first, so where do we stop with the testing?

**Comment by CrystalPea** [comment]
@benthorner I feel it still would be good to have a test about it, since it's a requirement that could affect the workings of gov.uk/alerts. So if someone were to alter the schema or something, they would at least see a failing test and reflect.

**Comment by benthorner** [comment]
@CrystalPea sure, I've amended the final commit so it includes a test / test data.

Could you take another look?

**Review by CrystalPea — APPROVED** [review]
Looks good to me. Only, is `'areas does not match ([a-zA-Z1-9]+ )*[a-zA-Z1-9]+'` the error that user will get? If so, we could do a better one, like 'We cannot accept empty area names' or something.

**Comment by benthorner** [comment]
> Only, is 'areas does not match ([a-zA-Z1-9]+ )*[a-zA-Z1-9]+' the error that user will get?

Yup. We don't control the errors though: this is the standard behaviour for JSON schema and [we let the user see these errors in other cases](https://github.com/alphagov/notifications-api/blob/4c7de35f68cedaf94d3326364e12872eaccd3931/tests/app/v2/broadcast/test_post_broadcast.py#L174). I'm going to merge this now as it's just a small bug I spotted and the main thing is that it's now protected by a validation. We can always try and rescue and customise the error message if someone reports it as confusing. On the positive side, the current error message makes it clear exactly what kinds of area names we _will_ accept, so let's see how it goes.

**Pull request merged**
