### PR TITLE
Create notification history from jobs

### PR DESCRIPTION
**Pull request by ashimali**
Db migration to retrospectively create notification history from jobs table.

The migration selects only jobs from after the go live date (18/05/2016) and before the earliest record in notification history table (2016-06-26 23:21:55).

This migration can only set outcome of notifications to either delivered or failed as jobs table has no data about temporary failure or other status.

Created at and sent at will be set to job creation time and job process finish time, and therefore will be different than actual timings.

Messages sent my amazon SES will have no reference ids.

### CODE REVIEW

**Comment by ashimali** [comment]
@servingUpAces and @minglis let me know if you're ok with this and the caveats in comment above.

**Comment by minglis** [comment]
Looks OK, best efforts after all. Going to get actual numbers from Prod and see what it behaves like.

**Comment by ashimali** [comment]
The select would return 1630 jobs
Of those number delivered is 84k and number failed is 73k records.

**Comment by minglis** [comment]
150k or so. We should test that.

**Pull request merged**
