### PR TITLE
Be more robust in handling ambiguous references to cancel an alert

### PR DESCRIPTION
**Pull request by quis**
We’ve found two problems that can come up when trying to cancel an alert:
- the `<references>` field contains reference to the alert which should be cancelled, plus some older, already-cancelled alerts
- the `<references>` field contains references to multiple current or pending alerts, and it’s unclear which one should be cancelled

This pull request adds code to handle the first case and error in the second.

### CODE REVIEW

**Comment by rjbaker** [comment]
From the CAP spec: 

> “Cancel” - Cancels the earlier message(s) identified in <references>

The reference fields behave like a linked list, usually there's original `Alert` followed by one or more `Update`s and a final `Cancel`. Usually an entirely new separate `Alert` will be created following a `Cancel` as it implies ALL referenced messages should be disregarded.

**Comment by quis** [comment]
@rjbaker we are letting people ‘reject’ (using a cancel message) alerts which are in the ‘pending approval‘ state. This is a state which isn’t in CAP. Therefore there’s more potential for ambiguity about which alert should be cancelled. The scenario we thought of is:
- someone issues an alert in the Flood Warning System
- they spot a spelling mistake
- they issue another alert in the Flood Warning System, to fix the spelling mistake 
- they try to cancel the original alert in the Flood Warning System
- the cancel now references the original alert and the corrected alert (this is how references work in the Flood Warning System)
- if we treat this a valid request we would reject the alert with the spelling mistake (good) but also the one with the correction (bad)

Operational procedures should stop this situation from arising, but if it does our preference is to have an error in the case of ambiguity, rather than risk cancelling something which should be going out. That’s what I’ve discussed with the Environment Agency.

**Comment by leohemsted** [comment]
if they end up in this state what would their course of action be - log into notify and manually cancel the one with the typo?

**Comment by quis** [comment]
@leohemsted yeah, that’s right.

**Review by rjbaker — APPROVED** [review]

**Pull request merged**
