### PR TITLE
Send count of sent letters to performance platform

### PR DESCRIPTION
**Pull request by quis**
Now we’ve been sending real letters for quite a while it would be nice to show how many.

### CODE REVIEW

**Comment by quis** [comment]
Tested with this curl command:
```shell
curl -X POST \
-d '{"_id": "MjAxOC0wMy0wMVQwMDowMDowMGdvdnVrLW5vdGlmeWxldHRlcm5vdGlmaWNhdGlvbnNkYXk=", "_timestamp": "2018-03-01T00:00:00", "service": "govuk-notify", "dataType": "notifications", "period": "day", "count": 1, "channel":"letter"}' \
-H 'Content-type: application/json' -H 'Authorization: Bearer <token>' https://www.performance.service.gov.uk/data/govuk-notify/notifications
```

**Comment by quis** [comment]
Showing our one letter:

image

**Comment by leohemsted** [comment]
do we want to back-populate this data?

**Comment by quis** [comment]
Yeah, looks like we can do it with this: https://github.com/alphagov/notifications-api/blob/f248234cfcf0e70cc5990a47579d68bff13ca6dc/app/commands.py#L212-L215

**Pull request merged**
