### PR TITLE
Let jobs be scheduled up to 7 days in the future 

### PR DESCRIPTION
**Pull request by quis**
4 days is sometimes not enough if there is a weekend with a bank holiday before and after it.

7 days is a sensible new limit because it:
- accounts for these longer weekends or holiday periods like Christmas
- without introducing any ambiguity about which ‘Thursday’ is meant (because only one of each weekday will ever be shown at once)

### CODE REVIEW

**Review by samuelhwilliams — APPROVED** [review]
I think this could go in (checked out locally and looks good).

But if we're providing these extra dates, I start to feel like including the date+month would be useful. Some people definitely will be date oriented (I want these messages to send on the 1st of the month) rather than day oriented, and I think in either case it helps to provide extra immediate clarity that these are all in the future.

So probably I'm suggesting/pondering:

* Today
* Tomorrow
* Sunday 8th October
* Monday 9th October
* Tuesday 10th October
* Wednesday 11th October
* Thursday 12th October

**Comment by quis** [comment]
The next page – once you have pressed the green button – presents the date like this:
image

**Comment by quis** [comment]
Would look like:

image

***

image


***

image

**Comment by karlchillmaid** [comment]
> But if we're providing these extra dates, I start to feel like including the date+month would be useful. Some people definitely will be date oriented (I want these messages to send on the 1st of the month) rather than day oriented, and I think in either case it helps to provide extra immediate clarity that these are all in the future.
> 
> So probably I'm suggesting/pondering:
> 
> * Today
> * Tomorrow
> * Sunday 8th October
> * Monday 9th October
> * Tuesday 10th October
> * Wednesday 11th October
> * Thursday 12th October
> 
> @karlchillmaid any thoughts? 🤔

I think this is a helpful addition, and Chris has already formatted the dates according to the style guide (no th or rd needed), so I’m happy 👍

**Pull request merged**
