### PR TITLE
Wrap exception to return a sensible message to the client

### PR DESCRIPTION
**Pull request by servingUpAces**
We are getting 500 errors when a POST notification has characters that can not be decoded or the json is malformed.

The exception is wrapped and a sensible error message is returned to the client.

### CODE REVIEW

**Comment by quis** [comment]
What does the error message say?

**Comment by servingUpAces** [comment]
The error message will be the "description" of the exception. 
For example: {error: BadRequestError: message: "'utf-8' codec can't decode byte 0xf8 in position 182: invalid start byte"}

**Comment by servingUpAces** [comment]
In conjunction with this we should take a look at the java client and see can either catch this early or fix the encoding of the string. Trouble is we haven't figured out how to reproduce the unicode error

**Comment by servingUpAces** [comment]
There is a story, https://www.pivotaltracker.com/story/show/158361458

**Pull request merged**
